spring:
  application:
    name: dolphin-id-generator
  datasource:
    url: jdbc:mysql://localhost:3306/dolphin-id-generator?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver