spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: sharding-eric
# 数据源 db01,db02
sharding:
  jdbc:
    datasource:
      names: db0,db1
      # 第一个数据库
      db0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver # 使用新版本驱动，则要指定区时serverTimezone
        jdbc-url: jdbc:mysql://localhost:3306/db0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      # 第二个数据库
      db1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    # 水平拆分的数据库（表） 配置分库 + 分表策略 行表达式分片策略
    config:
      sharding:
        ## 分库策略
        default-database-strategy:
          inline:
            sharding-column: id
            algorithm-expression: db$->{id % 2}
        ## 分表策略 其中user为逻辑表 分表主要取决于age行
        tables:
          user:
            actual-data-nodes: db$->{0..1}.user_$->{0..1}
            table-strategy:
              inline:
                sharding-column: age
                ### 分片算法表达式
                algorithm-expression: user_$->{age % 2}
      # 打印执行的数据库以及语句
      props:
        sql:
          show: true
# mybatis-plus映射mapper文件
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.eric.sharding.entity