spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: sharding-read-write
# 数据源 master0,slave1
sharding:
  jdbc:
    datasource:
      names: master0,slave1
      # 主数据库
      master0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver # 使用新版本驱动，则要指定区时serverTimezone
        jdbc-url: jdbc:mysql://localhost:3306/db0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      # 从数据库
      slave1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    # 配置读写分离
    config:
      masterslave:
        # 配置从库选择策略，提供轮询与随机，这里选择用轮询
        load-balance-algorithm-type: round_robin
        name: ms
        master-data-source-name: master0
        slave-data-source-names: slave1
      # 打印执行的数据库以及语句 仅配置读写分离时不会打印日志
      props:
        sql:
          show: true
# mybatis-plus映射mapper文件
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.eric.shardingreadwrite.entity