spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: signle-library-split-table
# 数据源 db0
sharding:
  jdbc:
    datasource:
      names: db0
      db0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver # 使用新版本驱动，则要指定区时serverTimezone
        jdbc-url: jdbc:mysql://localhost:3306/db0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    # 水平拆分的数据库（表） 配置分库 + 分表策略 行表达式分片策略
    config:
      sharding:
        ## 分表策略 其中user为逻辑表 分表主要取决于age行
        tables:
          user:
            # 指定user表的数据分布情况，配置数据节点 db0.user_0,db0.user_1
            actual-data-nodes: db0.user_$->{0..1}
            # 指定user表的主键及主键生成策略为SNOWFLAKE
            key-generator:
              column: id
              type: SNOWFLAKE
            # 指定user表的分片策略，分片策略包括分片键和分片算法
            table-strategy:
              inline:
                sharding-column: id
                ### 分片算法表达式
                algorithm-expression: user_$->{id % 2}
      # 打印执行的数据库以及语句
      props:
        sql:
          show: true
# mybatis-plus映射mapper文件
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.eric.sharding.entity